on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v17
      - uses: actions/checkout@v2
      - run: nix-build
      - run: date +%C
      - run: ./result/bin/g-date-time-format-test
