on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: cachix/install-nix-action@v17
      - uses: actions/checkout@v2
      - run: nix-build
      - run: date +%C
      - run: ./result/bin/g-date-time-format-test
      # https://github.com/NixOS/nixpkgs/commits/3fe874d773588e2fa6b678e8bb5bb8b127e75e68
      - run: nix-build -A tracker https://github.com/NixOS/nixpkgs/archive/3fe874d773588e2fa6b678e8bb5bb8b127e75e68.tar.gz
